nav:
  - Containers:
    - Azure Container Registry: Containers/Azure-Container-Registry.md
    - Azure Kubernetes Service: Containers/Azure-Kubernetes-Service.md
  - Databases:
    - Azure SQL: Databases/Azure-SQL.md
    - Cosmos DB: Databases/Cosmos-DB.md
  - Monitoring:
    - Security Center: Monitoring/Security-Center.md
  - Networking:
    - Application Gateway: Networking/Application-Gateway.md
    - Load Balancer: Networking/Load-Balancer.md
    - Traffic Manager: Networking/Traffic-Manager.md
  - Storage:
    - Azure Storage: Storage/Azure-Storage.md

site_name: Kusto Queries
theme:
  name: material
  logo: assets/AzureDataExplorerCluster.png
  favicon: assets/AzureDataExplorerCluster.png
  icon:
    repo: fontawesome/brands/github
  palette:
    primary: grey
    accent: light blue
  features:
    - navigation.top    
repo_url: https://github.com/LearnAzure/kusto-queries
repo_name: LearnAzure/kusto-queries
edit_uri: edit/main/docs/
extra_css: [extra.css]
plugins:
  - macros
  - search
  - pdf-export
copyright: Copyright &copy; 2018 - 2021 Joshua Davis &amp; <a href="https://LearnAzure.com">LearnAzure.com</a>
extra:
  chart:
    bar: <type-barchart></type-barchart>
    table: <type-table></type-table>
    time: <type-timechart></type-timechart>
    area: <type-areachart></type-areachart>
